upgrade the dependencies
ValentinnDimitroff/ra-compact-ui pull request #22
Opened 2022-07-04 18:51 UTC by morelmiles

Bump higher the React and React admin dependencies

2022-07-05 20:45 UTC, ValentinnDimitroff requested changes
Thank you for the PR! It really helped me get back to the library and spend some time maintenance! 

I'm ready to approve and merge once the comments are addressed.

2022-07-05 20:45 UTC, ValentinnDimitroff commented on package.json
>          "@material-ui/core": "^4.x",
Would you please update this one as well to: 

```
"@mui/icons-material": "^5.0.1",
"@mui/material": "^5.0.2",
```

2022-07-05 20:45 UTC, ValentinnDimitroff commented on examples/demo/src/components/projects/ProjectShow.jsx
> +                            <TextField source="priority" />
This is not needed
```suggestion
                            <TextField source="priority" />
```

2022-07-11 14:23 UTC, ofilipowicz commented
Patiently waiting for this PR to update my app to react-admin 4. Thanks guys!

2022-07-17 02:45 UTC, morelmiles commented
hey @ValentinnDimitroff, 
could you take a look? 

cheers,

2022-07-21 01:34 UTC, ValentinnDimitroff requested changes
Thank you for your recent commits! It took me some time exactly because it is not that simple to change consistently all packages' versions.

Since more and more people start using this library we should be very careful how we release a new version and there are some missing points still in the PR most of which hopefully I have pinned out. I've tried to make it as easy as possible for you to finish the changes.

Lastly - please run the `npm run prettier` script in the end to follow the formatting rules already set up in the project.

2022-07-21 01:34 UTC, ValentinnDimitroff commented on package.json
> +        "@mui/system": "^5.8.7",
This dependency is obsolete as it is actually dependency of `@mui/material`.

2022-07-21 01:34 UTC, ValentinnDimitroff commented on package.json
> +        "@emotion/react": "^11.9.3",
These two packages are dependencies of the `react-admin` package and are not needed here as it is already listed in the `peerDependencies`

2022-07-21 01:34 UTC, ValentinnDimitroff commented on package.json
> +        "@mui/styles": "^5.9.0",
This package will be deprecated in version 6 of MUI. Let's prepare and use the `@mui/material/styles` as advised here: 
https://stackoverflow.com/questions/69506133/difference-between-mui-material-styles-and-mui-styles 

This is especially important because we want people already using `react-admin` to add the library and NOT be required to install additional packages besides the ones coming through `react-admin` itself.

2022-07-21 01:34 UTC, ValentinnDimitroff commented on examples/demo/package.json
> +    "@mui/styles": "^5.9.0",
This one should not be needed ideally and also `react-admin` should be updated to some 4.x version so that the example projects proves our library actually works with the newer version.

2022-08-16 12:22 UTC, fkowal commented
hey wanted to ask about progress

2022-08-16 12:30 UTC, morelmiles commented
Hey, 
apologies. my bad.
i never saw the email notifications when @ValentinnDimitroff responded. 
will send fixes very soon by close of day. it's 15:30 here

2022-08-17 13:16 UTC, morelmiles commented
hey @ValentinnDimitroff 
please check the PR.

2022-12-03 11:53 UTC, the133448 commented
Hi @ValentinnDimitroff  any chance you could merge this PR? Would help support React admin v4!

2022-12-19 21:11 UTC, ValentinnDimitroff commented
@morelmiles could you give me access to your repository so I can push some changes and finally merge the PR?

2022-12-20 23:44 UTC, merged

2022-12-21 00:03 UTC, ValentinnDimitroff commented
Congrats everyone - `v2.0.0-beta` is now available @the133448 @morelmiles @fkowal @ofilipowicz